<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '9,10,11,12,13',
    'catname' => '电器',
    'style' => '',
    'image' => 'http://localhost/tyshop/uploadfile/2019/0528/20190528041438449.jpg',
    'description' => '',
    'parentdir' => '',
    'url' => '',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"meta_title":"","meta_keywords":"","meta_description":""}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'dianqi',
    'usable_type' => '',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '1',
    'arrchildid' => '10,11,12,13',
    'catname' => '手机',
    'style' => '',
    'image' => 'http://localhost/tyshop/uploadfile/2019/0528/20190528041438449.jpg',
    'description' => '',
    'parentdir' => '',
    'url' => '',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"meta_title":"","meta_keywords":"","meta_description":""}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shouji',
    'usable_type' => '',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '10',
    'arrparentid' => '0,9,10',
    'child' => '1',
    'arrchildid' => '11,12',
    'catname' => '品牌手机',
    'style' => '',
    'image' => 'http://localhost/tyshop/uploadfile/2019/0528/20190528041438449.jpg',
    'description' => '',
    'parentdir' => '',
    'url' => '',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"meta_title":"","meta_keywords":"","meta_description":""}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'pinpaishouji',
    'usable_type' => '',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '11',
    'arrparentid' => '0,9,10,11',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => '诺基亚',
    'style' => '',
    'image' => 'http://localhost/tyshop/uploadfile/2019/0528/20190528041438449.jpg',
    'description' => '',
    'parentdir' => '',
    'url' => '',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"meta_title":"","meta_keywords":"","meta_description":""}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'nuojiya',
    'usable_type' => '',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '10',
    'arrparentid' => '0,9,10',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '山寨机',
    'style' => '',
    'image' => 'http://localhost/tyshop/uploadfile/2019/0528/20190528041438449.jpg',
    'description' => '',
    'parentdir' => '',
    'url' => '',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"meta_title":"","meta_keywords":"","meta_description":""}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shanzhaiji',
    'usable_type' => '',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>